### ISSUE TITLE
Hack Gui

### ISSUE THREAD

**Issue by ReallyMan11** [ijustescapedyesterday/BlooketWorkingHacks#1]
When i use the daily tokens i can only use them once and i cant even earn any more tokens after that

**Comment by ijustescapedyesterday** [comment]
Hi! Thank you for Contacting us! 
Blooket itself has a feature, that you could only get up to 500 tokens, and 300 Xp, every 24 hours. That feature was written inside the system of Blooket, instead of the client side, so we could not modify the daily limit. Our claim daily rewards script could only cap out on the limit, but we could not bypass it. Thank you for your understanding.
